(() => {
  const nav=document.createElement('button');nav.dataset.page='proposals';nav.innerHTML=`${uiIcon('file')}<span>Proposals</span>`;
  document.querySelector('.nav [data-page="library"]').before(nav);
  const section=document.createElement('section');section.id='proposals';section.className='page';
  section.innerHTML='<div class="head proposal-page-head"><div><div class="eyebrow">Client documents</div><h1>Proposals</h1><p>Prepare a client quotation using your Corprights proposal template.</p></div><button class="btn primary" id="newProposal">New proposal</button></div><div class="proposal-status-tabs" role="tablist" aria-label="Proposal status"><button type="button" class="active" role="tab" aria-selected="true" data-proposal-status="draft">Draft <span>0</span></button><button type="button" role="tab" aria-selected="false" data-proposal-status="saved">Saved <span>0</span></button><button type="button" role="tab" aria-selected="false" data-proposal-status="sent">Sent <span>0</span></button></div><p class="muted">Save proposals under the client. Download and attach the PDF in WhatsApp or email, then Confirm sent to move the client to Proposal sent.</p><div id="proposalList" class="panel"></div>';
  document.querySelector('.content').append(section);
  const canEdit=()=>hasPermission('Edit leads');
  const date=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
  const proposalStatus=draft=>draft.sentAt||draft.status==='sent'?'sent':draft.status==='saved'?'saved':'draft';
  const statusLabel={draft:'Draft',saved:'Saved',sent:'Sent'};
  let activeStatus='draft';

  function proposalNumberPreview(){
    const settings={proposalPrefix:'NZ-PROP',includeYear:true,separator:'-',digits:4,proposalStart:1,...(account.numbering||{})};
    const references=[...leads,...(typeof deletedLeads==='undefined'?[]:deletedLeads)].flatMap(lead=>[lead.proposalNumber,...(lead.proposals||[]).map(proposal=>proposal.reference)]);
    const existingMax=references.reduce((highest,value)=>{const match=String(value||'').match(/(\d+)$/);return Math.max(highest,match?Number(match[1]):0);},0);
    const counter=Number(currentWorkspaceState()?.recordCounters?.proposalNumber?.value)||0;
    const sequence=Math.max(Number(settings.proposalStart)||1,existingMax+1,counter+1);
    const parts=[settings.proposalPrefix||'NZ-PROP'];if(settings.includeYear)parts.push(String(new Date().getFullYear()));parts.push(String(sequence).padStart(settings.digits,'0'));
    return parts.join(settings.separator||'-');
  }

  function allProposals(){return leads.flatMap(lead=>(lead.proposals||[]).map(draft=>({lead,draft,status:proposalStatus(draft)}))).sort((a,b)=>(b.draft.updatedAt||0)-(a.draft.updatedAt||0));}

  function render(){
    const list=section.querySelector('#proposalList');list.replaceChildren();section.querySelector('#newProposal').disabled=!canEdit();
    const records=allProposals(),counts={draft:0,saved:0,sent:0};records.forEach(record=>counts[record.status]++);
    section.querySelectorAll('[data-proposal-status]').forEach(button=>{const selected=button.dataset.proposalStatus===activeStatus;button.classList.toggle('active',selected);button.setAttribute('aria-selected',String(selected));button.querySelector('span').textContent=counts[button.dataset.proposalStatus];});
    const visible=records.filter(record=>record.status===activeStatus);
    if(!visible.length){const empty=document.createElement('div');empty.className='proposal-empty';empty.innerHTML=`${uiIcon(activeStatus==='sent'?'send':activeStatus==='saved'?'check':'edit')}<b>No ${statusLabel[activeStatus].toLowerCase()} proposals</b><span>${activeStatus==='draft'?'Create a proposal or save unfinished work as a draft.':activeStatus==='saved'?'Finalized proposals that have not been sent appear here.':'Confirmed deliveries appear here.'}</span>`;list.append(empty);}
    for(const {lead,draft,status:recordStatus} of visible){
      const row=document.createElement('div');row.className='setting-row proposal-row';const updated=new Date(draft.sentAt||draft.updatedAt||draft.createdAt||Date.now()).toLocaleString();
      const detail=recordStatus==='sent'?`${statusLabel[recordStatus]}${draft.sentVia?` via ${draft.sentVia}`:''} · ${updated}`:`${statusLabel[recordStatus]} · ${updated}`;
      row.innerHTML=`<div class="grow"><b>${safe(draft.reference||'Number assigned when saved')} · ${safe(lead.name)}</b><div class="muted">${safe(detail)}</div></div><span class="proposal-status ${recordStatus}">${statusLabel[recordStatus]}</span><button class="btn">${canEdit()?'Open / edit':'View'}</button>`;
      row.querySelector('button').onclick=()=>edit(lead,draft);list.append(row);
    }
  }
  section.querySelectorAll('[data-proposal-status]').forEach(button=>button.onclick=()=>{activeStatus=button.dataset.proposalStatus;render();});
  nav.onclick=()=>{closeLeadDrawer();page('proposals');render();};section.querySelector('#newProposal').onclick=()=>edit();
  const openBase=openLead;openLead=function(...args){const result=openBase(...args),actions=document.querySelector('#drawer .row-actions');if(actions&&!actions.querySelector('[data-proposal]')){const button=document.createElement('button');button.className='btn';button.dataset.proposal='';button.textContent='Proposals';button.onclick=()=>{const selected=leads[currentLead];closeLeadDrawer();page('proposals');render();edit(selected);};actions.append(button);}return result;};

  function edit(initialLead,existing){
    if(!existing&&!canEdit())return toast('Your role cannot create proposals');
    const me=currentUser(),draft=existing?structuredClone(existing):{id:crypto.randomUUID(),date:date(),reference:'',status:'draft',preparedBy:me.name||'',designation:me.designation||'Business Consultant',preparerPhone:me.phone||account.phone||'',preparerEmail:me.email||'',preparedFor:'',clientPhone:'',clientEmail:'',license:'Regular Investment Registration - Trading',structure:'100% Foreign Owned LLC',items:structuredClone(CrmProposalPdf.defaults),discount:5000,vat:0,exclusions:'Excluding applicable VAT. Fees related to employee Visa/Iqama, hiring employees, Saudization or PRO-related services are excluded.'};
    draft.status=proposalStatus(draft);
    const dialog=document.createElement('dialog');dialog.className='proposal-editor';dialog.setAttribute('aria-label','Proposal editor');
    dialog.innerHTML='<form><div class="head"><h2>Proposal editor</h2><button type="button" class="btn" data-close>Close</button></div><div class="formgrid" data-fields></div><h3>Quotation services</h3><div class="proposal-items"></div><button type="button" class="btn" data-add>Add service</button><div class="formgrid" data-totals></div><p class="proposal-total" aria-live="polite"></p><label class="field">Exclusions<textarea name="exclusions" rows="2" maxlength="650"></textarea></label><p class="muted">The remaining template pages are fixed, including scope, government fees and payment terms. Review them before sending. PDFs currently support Latin-script text.</p><label class="proposal-review"><input type="checkbox" name="reviewed" required> I will review the full proposal and confirm the fixed scope and terms are appropriate.</label><p role="status" data-status></p><div class="actions-end"><button type="button" class="btn" data-preview>Preview PDF</button><button type="button" class="btn" data-download>Download PDF</button><button type="button" class="btn" data-save-draft>Save draft</button><button type="submit" class="btn primary" data-save>Save</button></div><div data-output></div></form>';
    const form=dialog.querySelector('form'),fields=dialog.querySelector('[data-fields]'),status=dialog.querySelector('[data-status]');
    const noteLabel=document.createElement('label');noteLabel.className='field';noteLabel.innerHTML='Note<textarea name="note" rows="2" maxlength="500" placeholder="Optional note printed below Exclusions"></textarea>';form.elements.exclusions.closest('label').after(noteLabel);form.elements.note.value=draft.note||'';
    const clientField=document.createElement('label');clientField.className='field full';clientField.innerHTML=`Client<select name="client" required><option value="">Choose client</option>${leads.map(l=>`<option value="${safe(l.leadNumber)}">${safe(l.name)} · ${safe(l.leadNumber)}</option>`).join('')}</select>`;fields.append(clientField);
    const definitions=[['reference','Proposal reference preview'],['date','Date','date'],['preparedFor','Prepared for'],['clientPhone','Client phone'],['clientEmail','Client email','email'],['preparedBy','Prepared by'],['designation','Designation'],['preparerPhone','Preparer phone'],['preparerEmail','Preparer email','email'],['license','Proposed license'],['structure','Proposed structure']];
    for(const [name,label,type='text'] of definitions){const field=document.createElement('label');field.className=`field${name==='reference'?' proposal-reference-field':''}`;field.innerHTML=`${label}<input name="${name}" type="${type}" maxlength="160" ${['date','preparedFor','preparedBy'].includes(name)?'required':''}>`;fields.append(field);form.elements[name].value=name==='reference'?(draft.reference||proposalNumberPreview()):(draft[name]||'');}
    form.elements.reference.readOnly=true;form.elements.reference.setAttribute('aria-describedby','proposalReferenceHint');const referenceHint=document.createElement('small');referenceHint.id='proposalReferenceHint';referenceHint.className='muted';referenceHint.textContent=draft.reference?'This proposal number is assigned.':'Preview only - the number is assigned automatically when you save or send.';form.elements.reference.after(referenceHint);
    dialog.querySelector('[data-totals]').innerHTML='<label class="field">Discount (SAR)<input type="number" name="discount" min="0" step="0.01" required></label><label class="field">VAT (%)<input type="number" name="vat" min="0" max="100" step="0.01" required></label>';form.elements.discount.value=draft.discount;form.elements.vat.value=draft.vat;form.elements.exclusions.value=draft.exclusions;
    form.elements.client.value=initialLead?.leadNumber||'';form.elements.client.disabled=!!existing;
    function fillClient(){const lead=leads.find(l=>l.leadNumber===form.elements.client.value);if(!lead)return;form.elements.preparedFor.value=[lead.name,lead.company].filter(Boolean).join(' - ');form.elements.clientPhone.value=lead.phone||'';form.elements.clientEmail.value=lead.email||'';}
    form.elements.client.onchange=fillClient;if(initialLead&&!existing)fillClient();
    const itemList=dialog.querySelector('.proposal-items');
    function drawItems(){itemList.replaceChildren();draft.items.forEach((item,index)=>{const row=document.createElement('div');row.className='proposal-item';row.innerHTML=`<label class="field">Service ${index+1}<textarea required maxlength="600" rows="2" data-description></textarea></label><label class="field">Quantity<input required type="number" min="0.01" max="100000" step="0.01" data-quantity></label><label class="field">Unit price (SAR)<input required type="number" min="0" max="100000000" step="0.01" data-price></label><button type="button" class="btn danger" aria-label="Remove service ${index+1}">Remove</button>`;['description','quantity','price'].forEach(key=>{row.querySelector(`[data-${key}]`).value=item[key];row.querySelector(`[data-${key}]`).oninput=e=>{item[key]=key==='description'?e.target.value:Number(e.target.value);updateTotal();};});const catalog=document.createElement('select');catalog.setAttribute('aria-label',`Choose catalog product for service ${index+1}`);catalog.innerHTML='<option value="">Custom service / choose product</option>'+products.map((product,i)=>`<option value="${i}">${safe(product.name)}</option>`).join('');catalog.onchange=()=>{if(catalog.value==='')return;const product=products[Number(catalog.value)];item.description=product.name;item.price=Number(product.value)||0;drawItems();updateTotal();};row.querySelector('textarea').before(catalog);row.querySelector('button').onclick=()=>{draft.items.splice(index,1);drawItems();updateTotal();};itemList.append(row);});}
    function read(){definitions.filter(([name])=>name!=='reference').forEach(([name])=>draft[name]=form.elements[name].value);draft.discount=Number(form.elements.discount.value);draft.vat=Number(form.elements.vat.value);draft.exclusions=form.elements.exclusions.value;draft.note=form.elements.note.value;return draft;}
    function updateTotal(){try{const total=CrmProposalPdf.totals(read());dialog.querySelector('.proposal-total').textContent=`Total: SAR ${total.total.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;}catch(error){dialog.querySelector('.proposal-total').textContent=error.message;}}
    form.elements.discount.oninput=updateTotal;form.elements.vat.oninput=updateTotal;dialog.querySelector('[data-add]').onclick=()=>{if(draft.items.length>=10)return;draft.items.push({description:'',quantity:1,price:0});drawItems();updateTotal();};
    let pdfUrl;dialog.onclose=()=>{if(pdfUrl)URL.revokeObjectURL(pdfUrl);dialog.remove();};dialog.querySelector('[data-close]').onclick=()=>dialog.close();
    function selectedLead(){return leads.find(lead=>lead.leadNumber===form.elements.client.value);}
    function ensureReference(lead){if(draft.reference)return draft.reference;draft.reference=nextRecordNumber('NZ-PROP','proposalNumber');form.elements.reference.value=draft.reference;referenceHint.textContent='This proposal number is assigned.';lead.proposalNumber=draft.reference;return draft.reference;}
    function store(targetStatus){const lead=selectedLead();if(!lead)throw Error('Choose an available client.');read();CrmProposalPdf.totals(draft);ensureReference(lead);draft.status=targetStatus;draft.updatedAt=Date.now();draft.createdAt||=draft.updatedAt;lead.proposals=lead.proposals||[];const index=lead.proposals.findIndex(proposal=>proposal.id===draft.id);if(index<0)lead.proposals.push(structuredClone(draft));else lead.proposals[index]=structuredClone(draft);addTimeline(lead,targetStatus==='draft'?'Proposal draft saved':'Proposal saved',draft.reference);saveState();render();return lead;}
    async function build(assignReference=false){if(!form.reportValidity())return null;const data=read(),lead=selectedLead();if(!lead)throw Error('Choose an available client.');if(assignReference)ensureReference(lead);const pdfData={...data,reference:data.reference||proposalNumberPreview()};CrmProposalPdf.totals(pdfData);const response=await fetch('/assets/proposal-template.pdf');if(!response.ok)throw Error('Proposal template unavailable.');return {bytes:await CrmProposalPdf.generate(pdfData,await response.arrayBuffer()),reference:pdfData.reference};}
    async function output(download){if(!hasPermission('Export data')){status.textContent='Your role cannot export proposals.';return;}status.textContent='Preparing PDF...';try{const result=await build(false);if(!result){status.textContent='Complete the required fields first.';return;}if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl=URL.createObjectURL(new Blob([result.bytes],{type:'application/pdf'}));const link=document.createElement('a');link.href=pdfUrl;link.className='btn';link.textContent=download?'Download prepared PDF':'Open PDF preview';if(download)link.download=`${result.reference.replace(/[^a-z0-9_-]/gi,'_')}-Proposal.pdf`;else{link.target='_blank';link.rel='noopener';}const area=dialog.querySelector('[data-output]');area.replaceChildren(link);link.click();status.textContent='PDF ready. This has not been sent or marked as saved.';}catch(error){status.textContent=error.message;}}
    dialog.querySelector('[data-preview]').onclick=()=>output(false);dialog.querySelector('[data-download]').onclick=()=>output(true);
    dialog.querySelector('[data-save-draft]').onclick=()=>{if(!canEdit())return;try{store('draft');status.textContent='Draft saved to client. It has not been sent.';}catch(error){status.textContent=error.message;}};
    form.onsubmit=e=>{e.preventDefault();if(!canEdit())return;try{if(!form.reportValidity())return;const target=draft.status==='sent'?'sent':'saved';store(target);status.textContent=target==='sent'?'Changes saved. The proposal remains marked as sent.':'Proposal saved and ready to send.';}catch(error){status.textContent=error.message;}};
    const actions=dialog.querySelector('.actions-end'),sent=document.createElement('button');sent.type='button';sent.className='btn';sent.textContent='Confirm sent';sent.hidden=true;actions.append(sent);let pendingDelivery=null;
    for(const channel of ['WhatsApp','Email']){const button=document.createElement('button');button.type='button';button.className='btn proposal-channel-button';button.innerHTML=`${uiIcon(channel==='WhatsApp'?'whatsapp':'mail')}<span>Send via ${channel}</span>`;actions.insertBefore(button,sent);button.onclick=async()=>{if(!canEdit()||!hasPermission('Export data'))return;read();const phone=draft.clientPhone.replace(/\D/g,''),email=draft.clientEmail.trim();if(channel==='WhatsApp'&&!/^\d{8,15}$/.test(phone)){status.textContent='Enter the client phone including country code.';return;}if(channel==='Email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){status.textContent='Enter the client email first.';return;}try{const result=await build(true);if(!result)return;if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl=URL.createObjectURL(new Blob([result.bytes],{type:'application/pdf'}));const area=dialog.querySelector('[data-output]');area.replaceChildren();const download=document.createElement('a');download.href=pdfUrl;download.download=`${result.reference.replace(/[^a-z0-9_-]/gi,'_')}-Proposal.pdf`;download.textContent='1. Download PDF to attach';download.className='btn';area.append(download);const message=`Hello ${draft.preparedFor}, please find our proposal ${draft.reference} attached.`;const open=document.createElement('a');open.className='btn';open.textContent=`2. Open ${channel}`;open.target='_blank';open.rel='noopener';open.href=channel==='WhatsApp'?`https://wa.me/${phone}?text=${encodeURIComponent(message)}`:`mailto:${encodeURIComponent(email)}?subject=${encodeURIComponent('Proposal '+draft.reference)}&body=${encodeURIComponent(message)}`;area.append(open);const snapshot=JSON.stringify(read());pendingDelivery={channel,snapshot};sent.hidden=false;status.textContent=`Download the PDF, open ${channel}, attach it and send. Then click Confirm sent. Opening the app does not send or attach the PDF automatically.`;}catch(error){status.textContent=error.message;}};}
    sent.onclick=()=>{if(!canEdit()||!pendingDelivery)return;if(JSON.stringify(read())!==pendingDelivery.snapshot){status.textContent='The proposal changed. Prepare it again before confirming delivery.';return;}const lead=selectedLead(),stageIndex=stages.findIndex(stage=>/^proposal sent$/i.test(stage[0]));if(!lead||stageIndex<0){status.textContent='A Proposal sent stage is required in the pipeline.';return;}if(['Won','Lost'].includes(lead.status)){status.textContent='This deal is closed. Reopen it explicitly before changing its stage.';return;}if(!confirm(`Confirm you attached and sent proposal ${draft.reference} via ${pendingDelivery.channel}? This moves the client to Proposal sent.`))return;draft.sentAt=Date.now();draft.sentVia=pendingDelivery.channel;draft.status='sent';draft.updatedAt=draft.sentAt;draft.createdAt||=draft.sentAt;lead.proposals=lead.proposals||[];const index=lead.proposals.findIndex(proposal=>proposal.id===draft.id);if(index<0)lead.proposals.push(structuredClone(draft));else lead.proposals[index]=structuredClone(draft);lead.proposalNumber=draft.reference;commitPipelineStage(leads.indexOf(lead),stageIndex,lead.pipeline);addTimeline(lead,'Proposal sent (user confirmed)',`${draft.reference} · ${draft.sentVia}`);saveState();renderLeads();renderBoard();activeStatus='sent';render();sent.hidden=true;pendingDelivery=null;status.textContent='Sending confirmed. Client moved to Proposal sent.';};
    document.body.append(dialog);drawItems();updateTotal();if(!canEdit())form.querySelectorAll('input,select,textarea,button[type="submit"],[data-save-draft],[data-add],.proposal-item button').forEach(element=>element.disabled=true);dialog.showModal();
  }
  render();
})();
